### ISSUE TITLE
報錯

### ISSUE THREAD

**Issue by david082321** [mthli/Mount#1]
> java.lang.IllegalStateException: Not allowed to set the device owner because there are already several users on the device
        at android.os.Parcel.readException(Parcel.java:1629)
        at android.os.Parcel.readException(Parcel.java:1574)
        at android.app.admin.IDevicePolicyManager$Stub$Proxy.setDeviceOwner(IDevicePolicyManager.java:5146)
        at com.android.commands.dpm.Dpm.runSetDeviceOwner(Dpm.java:114)
        at com.android.commands.dpm.Dpm.onRun(Dpm.java:82)
        at com.android.internal.os.BaseCommand.run(BaseCommand.java:47)
        at com.android.commands.dpm.Dpm.main(Dpm.java:38)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:257)

**Comment by david082321** [comment]
与三星konx安全文件夹冲突，无法同时使用

**Comment by mthli** [comment]
那你还是用 KNOX 吧。
