### ISSUE TITLE
执行Adb命令时异常

### ISSUE THREAD

**Issue by LeonXtp** [mthli/Mount#5]
android.os.DeadObjectException
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(Binder.java:615)
	at android.app.admin.IDevicePolicyManager$Stub$Proxy.removeActiveAdmin(IDevicePolicyManager.java:4521)
	at com.android.commands.dpm.Dpm.runSetDeviceOwner(Dpm.java:154)
	at com.android.commands.dpm.Dpm.onRun(Dpm.java:96)
	at com.android.internal.os.BaseCommand.run(BaseCommand.java:51)
	at com.android.commands.dpm.Dpm.main(Dpm.java:41)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:262)

**Comment by mthli** [comment]
系统设置里的帐号必须移除干净。

**Comment by LeonXtp** [comment]
@mthli 那里有几个账号是无法移除的，没有移除的选项

**Comment by mthli** [comment]
那就无能为力了。
